-- 브랜드
insert into brands (name, name_ko) values
  ('Good Smile Company', '굿스마일'),
  ('Bandai', '반다이'),
  ('Kotobukiya', '코토부키야'),
  ('Max Factory', '맥스팩토리'),
  ('Alter', '알터');

-- 카테고리
insert into categories (name, slug, priority) values
  ('애니메이션', 'anime', 1),
  ('게임', 'game', 2),
  ('스포츠', 'sports', 3),
  ('영화', 'movie', 4);

-- 시리즈
insert into series (name, name_ko, brand_id) values
  ('One Piece', '원피스', (select id from brands where name = 'Bandai')),
  ('Demon Slayer', '귀멸의 칼날', (select id from brands where name = 'Good Smile Company')),
  ('Hololive', '홀로라이브', (select id from brands where name = 'Good Smile Company')),
  ('Final Fantasy', '파이널판타지', (select id from brands where name = 'Kotobukiya'));

-- 상품 20개
insert into products (name, name_ko, price, original_price, brand_id, series_id, category_id, stock, scale, is_active, is_featured) values
  ('Monkey D. Luffy', '몽키 D. 루피', 89000, null,
    (select id from brands where name = 'Bandai'),
    (select id from series where name = 'One Piece'),
    (select id from categories where slug = 'anime'),
    10, '1/8', true, true),
  ('Roronoa Zoro', '롤로노아 조로', 95000, 110000,
    (select id from brands where name = 'Bandai'),
    (select id from series where name = 'One Piece'),
    (select id from categories where slug = 'anime'),
    5, '1/8', true, true),
  ('Tanjiro Kamado', '카마도 탄지로', 79000, null,
    (select id from brands where name = 'Good Smile Company'),
    (select id from series where name = 'Demon Slayer'),
    (select id from categories where slug = 'anime'),
    8, '1/7', true, true),
  ('Nezuko Kamado', '카마도 네즈코', 75000, 85000,
    (select id from brands where name = 'Good Smile Company'),
    (select id from series where name = 'Demon Slayer'),
    (select id from categories where slug = 'anime'),
    3, '1/7', true, false),
  ('Hatsune Miku', '하츠네 미쿠', 135000, null,
    (select id from brands where name = 'Good Smile Company'),
    null,
    (select id from categories where slug = 'anime'),
    12, 'Nendoroid', true, true),
  ('Cloud Strife', '클라우드 스트라이프', 185000, 210000,
    (select id from brands where name = 'Kotobukiya'),
    (select id from series where name = 'Final Fantasy'),
    (select id from categories where slug = 'game'),
    4, '1/6', true, true),
  ('Tifa Lockhart', '티파 록하트', 175000, null,
    (select id from brands where name = 'Kotobukiya'),
    (select id from series where name = 'Final Fantasy'),
    (select id from categories where slug = 'game'),
    6, '1/6', true, false),
  ('Aerith Gainsborough', '에어리스 게인즈버러', 165000, 190000,
    (select id from brands where name = 'Alter'),
    (select id from series where name = 'Final Fantasy'),
    (select id from categories where slug = 'game'),
    2, '1/7', true, true),
  ('Son Goku', '손오공', 99000, null,
    (select id from brands where name = 'Bandai'),
    null,
    (select id from categories where slug = 'anime'),
    15, 'S.H.Figuarts', true, false),
  ('Vegeta', '베지터', 99000, 115000,
    (select id from brands where name = 'Bandai'),
    null,
    (select id from categories where slug = 'anime'),
    7, 'S.H.Figuarts', true, false),
  ('Link', '링크', 145000, null,
    (select id from brands where name = 'Good Smile Company'),
    null,
    (select id from categories where slug = 'game'),
    9, '1/7', true, true),
  ('Samus Aran', '사무스 아란', 155000, 175000,
    (select id from brands where name = 'Good Smile Company'),
    null,
    (select id from categories where slug = 'game'),
    3, '1/8', true, false),
  ('Iron Man', '아이언맨', 125000, null,
    (select id from brands where name = 'Bandai'),
    null,
    (select id from categories where slug = 'movie'),
    11, 'S.H.Figuarts', true, true),
  ('Spider-Man', '스파이더맨', 115000, 130000,
    (select id from brands where name = 'Bandai'),
    null,
    (select id from categories where slug = 'movie'),
    8, 'S.H.Figuarts', true, false),
  ('Batman', '배트맨', 135000, null,
    (select id from brands where name = 'Kotobukiya'),
    null,
    (select id from categories where slug = 'movie'),
    5, '1/6', true, false),
  ('Makima', '마키마', 145000, 165000,
    (select id from brands where name = 'Good Smile Company'),
    null,
    (select id from categories where slug = 'anime'),
    4, '1/7', true, true),
  ('Denji', '덴지', 95000, null,
    (select id from brands where name = 'Max Factory'),
    null,
    (select id from categories where slug = 'anime'),
    6, 'Figma', true, false),
  ('Lara Croft', '라라 크로프트', 195000, 220000,
    (select id from brands where name = 'Kotobukiya'),
    null,
    (select id from categories where slug = 'game'),
    2, '1/6', true, false),
  ('Asuka Langley', '아스카 랑레이', 155000, null,
    (select id from brands where name = 'Alter'),
    null,
    (select id from categories where slug = 'anime'),
    7, '1/7', true, false),
  ('Rei Ayanami', '레이 아야나미', 149000, 169000,
    (select id from brands where name = 'Alter'),
    null,
    (select id from categories where slug = 'anime'),
    5, '1/7', true, false);
